### ISSUE TITLE
Enchancement: Making branches for different versions rather than commiting to master.

### ISSUE THREAD

**Issue by DUFCLiam** [RainbowFreedomDev/FreedomBot#3]
This shall make code cleaner when searching for the current version

**Comment by FoxIshDaBest** [comment]
Alright

**Comment by FoxIshDaBest** [comment]
I just noticed, I never made v1.5. I skipped it because TFM 5.0 came out xD

**Comment by FoxIshDaBest** [comment]
This isnt really needed. I don't think anyone would want to downgrade. The lower versions of freedombot are really buggy and dont work well. I will plan on doing this later on though.

**Comment by DUFCLiam** [comment]
We can keep the previous version though.

**Comment by FoxIshDaBest** [comment]
Mhm

**Comment by AvalancheYT** [comment]
Older version must be stable before moving onto different version.

**Comment by DUFCLiam** [comment]
Also repo has moved; Read the readme.
